### ISSUE TITLE
Update needed to parse-server#latest

### ISSUE THREAD

**Issue by flovilmart** [lcortess/simple-parse-smtp-adapter#1]
We updated parse-server to reflect the behaviour on parse.com, therefore, the email may be in user.get('username') in some cases.

https://github.com/lcortess/simple-parse-smtp-adapter/blob/master/index.js#L75

You should take that into account  :)

See: https://github.com/ParsePlatform/parse-server/pull/2732

**Comment by lcortess** [comment]
Thanks for your advice, I've added a method for search the email in the email field and if no exist return the username, also I added an optional option for define a specific field for the user email

**Comment by flovilmart** [comment]
Great!
