### ISSUE TITLE
Google SMTP

### ISSUE THREAD

**Issue by tru3d3v** [lcortess/simple-parse-smtp-adapter#15]
Hi,

I am using google smtp for my email adapter, when i try to reset my password i got some error:

{ Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)

can you advice me?

Thank you

**Comment by kitaecc** [comment]
Hi, can u  edit in  smtp-adapter module  file  index.js



   let transporter = nodemailer.createTransport({
     ...
        tls: {
            rejectUnauthorized: false //remove parameter and put false
        }
    });

and test u send mail

**Comment by tru3d3v** [comment]
Hi, Thank you for your advice, but still mark as spam if i use google smtp. I waiting for approval pull request for this problem. you check compare code from master 
https://github.com/lcortess/simple-parse-smtp-adapter/pull/16/commits/b18162daaceb35cf2c29331daccf4df608daa1bf
