### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by prakash-subramani** [lcortess/simple-parse-smtp-adapter#4]
I'm facing this problem with AWS host

`[Error: Hostname/IP doesn't match certificate's altnames: "Host: ***.com. is not in the cert's altnames: DNS:*.inmotionhosting.com, DNS:inmotionhosting.com"]`

The error happens only while send mail from cloud server. But locally it works fine.

**Comment by lcortess** [comment]
Did you resolve your problem? I am using this module on AWS and works fine

**Comment by prakash-subramani** [comment]
Yes. the following code fixes my problem but i don't know this is the right way to solve.

`tls: {
            rejectUnauthorized: false
        }`
