### ISSUE TITLE
No email sent and no errors reported

### ISSUE THREAD

**Issue by jsheets** [lcortess/simple-parse-smtp-adapter#9]
I set up the emailAdapter with a Gmail account. The Parse Server claims to successfully send a password reset email, but no email arrives and I can't find any logging of any action anywhere.

I even tried entering the wrong password but it does not throw an error. Silent failure.

**Comment by g3r4n** [comment]
Can you give an other try ? the adaptor logs error now.

**Comment by jsheets** [comment]
I ended up going with Amazon SES instead so I guess it's moot for me now. Thanks, though!
